#!/usr/bin/bash

SCRIPT_DIR="$(dirname "$(realpath "$0")")"
INPUT="$1"

FILE_NAME=$(basename "$1")
OUTPUT="${FILE_NAME%.c}"

shift

# Read the first line of the .c file
FIRST_LINE=$(head -n 1 "$INPUT")

# Check if the first line starts with //!FLAGS:
if [[ $FIRST_LINE =~ ^//FLAGS:\ (.*) ]]; then
  FLAGS=${BASH_REMATCH[1]}
  set -- $FLAGS "$@"
fi

mkdir -p "$SCRIPT_DIR/bin"
gcc "$INPUT" -o "$SCRIPT_DIR/bin/$OUTPUT" "$@"

if [ $? -ne 0 ]; then
  echo "Compilation failed."
  exit 1
fi

"$SCRIPT_DIR/bin/$OUTPUT"
